"""add review_queue table

Revision ID: 14f544f16a8c
Revises: ee11c9066b2e
Create Date: 2026-09-24 00:55:44.482656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14f544f16a8c'
down_revision: Union[str, Sequence[str], None] = 'ee11c9066b2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_queue',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('term_data', sa.Text(), nullable=False),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('source_file', sa.String(length=512), nullable=False),
    sa.Column('confidence', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review_queue'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review_queue')
    # ### end Alembic commands ###
