"""add document_chunks table

Revision ID: 3c6f4f21ca8c
Revises: 14f544f16a8c
Create Date: 2026-09-24 15:49:07.085993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c6f4f21ca8c'
down_revision: Union[str, Sequence[str], None] = '14f544f16a8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_chunks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('text', sa.String(length=4096), nullable=False),
    sa.Column('source_file', sa.String(length=512), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('char_start', sa.Integer(), nullable=False),
    sa.Column('char_end', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_chunks')),
    sa.UniqueConstraint('source_file', 'chunk_index', name='uq_document_chunks_source_file_index')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('document_chunks')
    # ### end Alembic commands ###
