"""Extract candidate terms from documented class/Protocol names (ADR-0004's
Medium-confidence "Docstrings + class/Protocol names" source).

Deterministic, no LLM (ADR-0004's Extract stage). A class with no
docstring has no definition seed for the enrich stage to ground on, so
those are skipped rather than extracted with an empty description.

Two structural filters, not name-pattern heuristics:
- `api/` layer is skipped entirely. Every service's transport DTOs
  (FastAPI request/response schemas, GraphQL types) live there, named
  after wire shape (`CreateRoundRequest`, `GameConfigResponse`), not
  vocabulary - the layering ADR-0003 already enforces gives this
  extractor a clean boundary for free.
- Private classes (leading underscore) are skipped - internal
  implementation detail by convention, not a term to teach.

What's left through (`SQLTermRepository`, `TermModel`) is still noisier
than the ADR-heading source - ADR-0004 names this tradeoff explicitly
("project-local jargon, not industry vocabulary") and leaves it to
review, same as the other two extractors.
"""

from __future__ import annotations

import ast
from pathlib import Path

from pipeline_service.candidate import Confidence
from pipeline_service.candidate import SourceType
from pipeline_service.candidate import TermCandidate

_SERVICE_PACKAGE_DIRS = (
    "game_service",
    "content_service",
    "pipeline_service",
)


def find_source_files(repo_root: Path) -> tuple[Path, ...]:
    """Every .py file under a service's own package (not its api/ layer,
    tests, migrations, or generated protobuf stubs), across services/
    and libs/.
    """
    files: list[Path] = []
    for base in (repo_root / "services", repo_root / "libs"):
        for path in sorted(base.rglob("*.py")):
            parts = path.parts
            if "api" in parts or "tests" in parts or "alembic" in parts:
                continue
            if "__pycache__" in parts or ".venv" in parts:
                continue
            if path.stem.endswith("_pb2") or path.stem.endswith("_pb2_grpc"):
                continue  # generated by the protobuf compiler, not hand-written
            if not any(pkg in parts for pkg in _SERVICE_PACKAGE_DIRS) and (
                "src" not in parts
            ):
                continue
            files.append(path)
    return tuple(files)


def extract_from_file(path: Path) -> tuple[TermCandidate, ...]:
    """Parse one module's top-level and nested class definitions.
    Undocumented and private (leading-underscore) classes are skipped.
    """
    try:
        tree = ast.parse(path.read_text())
    except SyntaxError:
        return ()

    candidates: dict[str, TermCandidate] = {}
    for node in ast.walk(tree):
        if not isinstance(node, ast.ClassDef):
            continue
        if node.name.startswith("_"):
            continue
        if ast.get_docstring(node) is None:
            continue
        candidates.setdefault(
            node.name,
            TermCandidate(
                name=node.name,
                source_type=SourceType.CLASS_NAME,
                source_file=str(path),
                confidence=Confidence.MEDIUM,
            ),
        )

    return tuple(candidates.values())


def extract_class_names(repo_root: Path) -> tuple[TermCandidate, ...]:
    """Extract candidates from every service's source, deduplicated by
    name (a class name reused across services/modules yields one
    candidate, keeping the first file it was seen in).
    """
    seen: dict[str, TermCandidate] = {}
    for path in find_source_files(repo_root):
        for candidate in extract_from_file(path):
            seen.setdefault(candidate.name, candidate)
    return tuple(seen.values())
