# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from term_proto import term_pb2 as term__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in term_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TermServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetById = channel.unary_unary(
                '/termrush.content.v1.TermService/GetById',
                request_serializer=term__pb2.GetByIdRequest.SerializeToString,
                response_deserializer=term__pb2.TermReply.FromString,
                _registered_method=True)
        self.GetRandom = channel.unary_unary(
                '/termrush.content.v1.TermService/GetRandom',
                request_serializer=term__pb2.GetRandomRequest.SerializeToString,
                response_deserializer=term__pb2.TermReply.FromString,
                _registered_method=True)
        self.ListCategories = channel.unary_unary(
                '/termrush.content.v1.TermService/ListCategories',
                request_serializer=term__pb2.ListCategoriesRequest.SerializeToString,
                response_deserializer=term__pb2.ListCategoriesReply.FromString,
                _registered_method=True)


class TermServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def GetById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRandom(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListCategories(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TermServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetById,
                    request_deserializer=term__pb2.GetByIdRequest.FromString,
                    response_serializer=term__pb2.TermReply.SerializeToString,
            ),
            'GetRandom': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRandom,
                    request_deserializer=term__pb2.GetRandomRequest.FromString,
                    response_serializer=term__pb2.TermReply.SerializeToString,
            ),
            'ListCategories': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCategories,
                    request_deserializer=term__pb2.ListCategoriesRequest.FromString,
                    response_serializer=term__pb2.ListCategoriesReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'termrush.content.v1.TermService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('termrush.content.v1.TermService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TermService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/termrush.content.v1.TermService/GetById',
            term__pb2.GetByIdRequest.SerializeToString,
            term__pb2.TermReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRandom(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/termrush.content.v1.TermService/GetRandom',
            term__pb2.GetRandomRequest.SerializeToString,
            term__pb2.TermReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListCategories(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/termrush.content.v1.TermService/ListCategories',
            term__pb2.ListCategoriesRequest.SerializeToString,
            term__pb2.ListCategoriesReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
