# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: term.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'term.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nterm.proto\x12\x13termrush.content.v1\"!\n\x0eGetByIdRequest\x12\x0f\n\x07term_id\x18\x01 \x01(\t\"\xee\x01\n\x10GetRandomRequest\x12\x14\n\x0c\x65xcluded_ids\x18\x01 \x03(\t\x12\x15\n\x08\x63\x61tegory\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x1b\n\x0emin_difficulty\x18\x03 \x01(\x05H\x01\x88\x01\x01\x12\x1d\n\x10require_examples\x18\x04 \x01(\x08H\x02\x88\x01\x01\x12\"\n\x15min_definition_length\x18\x05 \x01(\x05H\x03\x88\x01\x01\x42\x0b\n\t_categoryB\x11\n\x0f_min_difficultyB\x13\n\x11_require_examplesB\x18\n\x16_min_definition_length\"\x17\n\x15ListCategoriesRequest\")\n\x13ListCategoriesReply\x12\x12\n\ncategories\x18\x01 \x03(\t\"\xe8\x01\n\tTermReply\x12\r\n\x05\x66ound\x18\x01 \x01(\x08\x12\n\n\x02id\x18\x02 \x01(\t\x12\x0c\n\x04term\x18\x03 \x01(\t\x12\x11\n\texpansion\x18\x04 \x01(\t\x12\x13\n\x0b\x64\x65\x66initions\x18\x05 \x03(\t\x12\x0f\n\x07\x61liases\x18\x06 \x03(\t\x12\x12\n\ncategories\x18\x07 \x03(\t\x12\x12\n\ndifficulty\x18\x08 \x01(\x05\x12\x10\n\x08\x65xamples\x18\t \x03(\t\x12\x0f\n\x07related\x18\n \x03(\t\x12\x15\n\rprerequisites\x18\x0b \x03(\t\x12\x17\n\x0f\x63ommon_mistakes\x18\x0c \x03(\t2\x99\x02\n\x0bTermService\x12N\n\x07GetById\x12#.termrush.content.v1.GetByIdRequest\x1a\x1e.termrush.content.v1.TermReply\x12R\n\tGetRandom\x12%.termrush.content.v1.GetRandomRequest\x1a\x1e.termrush.content.v1.TermReply\x12\x66\n\x0eListCategories\x12*.termrush.content.v1.ListCategoriesRequest\x1a(.termrush.content.v1.ListCategoriesReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'term_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETBYIDREQUEST']._serialized_start=35
  _globals['_GETBYIDREQUEST']._serialized_end=68
  _globals['_GETRANDOMREQUEST']._serialized_start=71
  _globals['_GETRANDOMREQUEST']._serialized_end=309
  _globals['_LISTCATEGORIESREQUEST']._serialized_start=311
  _globals['_LISTCATEGORIESREQUEST']._serialized_end=334
  _globals['_LISTCATEGORIESREPLY']._serialized_start=336
  _globals['_LISTCATEGORIESREPLY']._serialized_end=377
  _globals['_TERMREPLY']._serialized_start=380
  _globals['_TERMREPLY']._serialized_end=612
  _globals['_TERMSERVICE']._serialized_start=615
  _globals['_TERMSERVICE']._serialized_end=896
# @@protoc_insertion_point(module_scope)
